apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollapp
spec:
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
        version: "1.0.0"
    spec:
      containers:
      - name: application
        image: ahmedgabercod/rollapp:1.0.0
        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 5